In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("D:\\newproject\\New folder\\Sorghum.data.csv")

In [4]:
#Na Handling
df.isnull().values.any()

True

In [5]:
df=df.dropna()

In [6]:
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [7]:
X = df.drop(['Predictor'], axis=1)
X_col = X.columns

In [8]:
y = df['Predictor']

In [9]:

#Savitzky-Golay filter with second degree derivative.
from scipy.signal import savgol_filter 

sg=savgol_filter(X,window_length=11, polyorder=3, deriv=2, delta=1.0)

C:\Users\akhil\Anaconda3\lib\site-packages\scipy\signal\_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]


In [10]:
sg_x=pd.DataFrame(sg, columns=X_col)
sg_x.head()

740       741       742       743       744       745       746  \
0  0.000313  0.000282  0.000250  0.000218  0.000186  0.000154  0.000121   
1  0.000259  0.000235  0.000210  0.000185  0.000161  0.000136  0.000110   
2  0.000225  0.000203  0.000181  0.000158  0.000136  0.000114  0.000090   
3  0.000158  0.000150  0.000141  0.000133  0.000125  0.000117  0.000105   
4  0.000316  0.000287  0.000257  0.000228  0.000198  0.000169  0.000138   

        747       748           749    ...         1061      1062      1063  \
0  0.000079  0.000037  4.515035e-07    ...    -0.000507 -0.000523 -0.000332   
1  0.000071  0.000029 -7.377783e-06    ...    -0.000534 -0.000550 -0.000346   
2  0.000058  0.000023 -5.902443e-06    ...    -0.000508 -0.000524 -0.000334   
3  0.000078  0.000045  1.314993e-05    ...    -0.000520 -0.000536 -0.000336   
4  0.000096  0.000053  1.504493e-05    ...    -0.000507 -0.000522 -0.000331   

       1064      1065      1066      1067      1068      1069      1070  
0 -0.000003  0.000329  0.000805  0.001281  0.001757  0.002233  0.002709  
1  0.000004  0.000357  0.000864  0.001370  0.001877  0.002384  0.002890  
2 -0.000009  0.000321  0.000794  0.001266  0.001739  0.002211  0.002684  
3  0.000006  0.000351  0.000846  0.001341  0.001835  0.002330  0.002825  
4 -0.000004  0.000327  0.000801  0.001276  0.001750  0.002225  0.002699  

[5 rows x 331 columns]

In [11]:

#from sklearn import preprocessing

In [12]:
#StandardScaler_X =preprocessing.StandardScaler().fit_transform(X.values)

In [13]:
#df10 = pd.DataFrame(StandardScaler_X)

In [14]:
#df10.head()

In [15]:
from sklearn.decomposition import PCA as sklearnPCA
sklearn_pca = sklearnPCA(n_components=100)
X_sklearn = sklearn_pca.fit_transform(sg_x)

In [16]:
df15 = pd.DataFrame(X_sklearn)

In [17]:
df15.head()

0         1         2         3         4             5         6   \
0 -0.002404 -0.000119 -0.000020 -0.000126 -0.000109 -7.893449e-05  0.000034   
1 -0.002699 -0.000174 -0.000003 -0.000050 -0.000038 -4.339183e-05  0.000003   
2 -0.002353 -0.000195 -0.000019  0.000017 -0.000072 -9.375287e-05  0.000031   
3 -0.002588 -0.000249 -0.000004  0.000096 -0.000097  2.000890e-07 -0.000021   
4 -0.002394 -0.000100 -0.000021 -0.000141 -0.000118 -4.438844e-05  0.000046   

         7         8         9       ...                 90            91  \
0  0.000020 -0.000044  0.000039      ...       2.788098e-08  6.573589e-09   
1 -0.000075 -0.000045 -0.000015      ...       1.924276e-08  2.181918e-08   
2  0.000015 -0.000057  0.000034      ...      -2.304593e-08  7.890062e-09   
3 -0.000099 -0.000066 -0.000021      ...      -2.210283e-08  8.126729e-09   
4  0.000002 -0.000048  0.000025      ...      -2.963909e-08 -7.483010e-10   

             92            93            94            95            96  \
0 -1.387546e-08 -2.518892e-09  1.549244e-09  9.579188e-09  4.890060e-09   
1  2.454316e-08 -8.791493e-09  1.158286e-08  9.930704e-09 -5.405063e-09   
2  1.018321e-08 -1.214092e-08 -1.763211e-08  1.951686e-09  1.988244e-10   
3  2.566848e-08 -1.687320e-08  5.390133e-09 -1.285203e-08 -3.990686e-09   
4 -1.279323e-08  1.029926e-08 -4.664760e-09 -4.876027e-09  1.683188e-08   

             97            98            99  
0  2.282474e-08  9.565566e-09 -1.771674e-09  
1 -1.267590e-08 -7.156902e-09 -6.042039e-09  
2  1.611129e-08  1.202233e-09 -4.235050e-09  
3 -4.208276e-09 -2.960097e-10  1.475797e-08  
4  4.633865e-09  4.844405e-09  5.412826e-09  

[5 rows x 100 columns]

In [18]:
df15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 100 columns):
0     500 non-null float64
1     500 non-null float64
2     500 non-null float64
3     500 non-null float64
4     500 non-null float64
5     500 non-null float64
6     500 non-null float64
7     500 non-null float64
8     500 non-null float64
9     500 non-null float64
10    500 non-null float64
11    500 non-null float64
12    500 non-null float64
13    500 non-null float64
14    500 non-null float64
15    500 non-null float64
16    500 non-null float64
17    500 non-null float64
18    500 non-null float64
19    500 non-null float64
20    500 non-null float64
21    500 non-null float64
22    500 non-null float64
23    500 non-null float64
24    500 non-null float64
25    500 non-null float64
26    500 non-null float64
27    500 non-null float64
28    500 non-null float64
29    500 non-null float64
30    500 non-null float64
31    500 non-null float64
32    500 non-null float64
33 

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_sklearn, y,
                                                    train_size=0.7,
                                                    random_state=42,stratify = y)

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [21]:
def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
        print("Classification Report: \n {}\n".format(classification_report(y_train, clf.predict(X_train))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, clf.predict(X_train))))

        res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        print("Test Result:\n")        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
        print("Classification Report: \n {}\n".format(classification_report(y_test, clf.predict(X_test))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, clf.predict(X_test)))) 

In [22]:
from sklearn import svm
clf = svm.SVC(kernel="linear")
clf.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [23]:
print_score(clf, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.4771

Classification Report: 
                precision    recall  f1-score   support

      76TI#23       0.00      0.00      0.00        35
       Abshir       0.00      0.00      0.00        35
       Birhan       0.00      0.00      0.00        35
       Dekeba       0.74      0.97      0.84        35
Gambella_1107       0.47      1.00      0.64        35
       Gubiye       0.64      0.97      0.77        35
        Macia       0.38      0.83      0.52        35
       Meko-1       0.35      1.00      0.52        35
       Melkam       0.00      0.00      0.00        35
      Teshale       0.00      0.00      0.00        35

    micro avg       0.48      0.48      0.48       350
    macro avg       0.26      0.48      0.33       350
 weighted avg       0.26      0.48      0.33       350


Confusion Matrix: 
 [[ 0  0  0  0 19  4 12  0  0  0]
 [ 0  0  0  0  0  1 13 21  0  0]
 [ 0  0  0  0  0  1  3 31  0  0]
 [ 0  0  0 34  0  1  0  0  0  0]
 [ 0  0  0

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Average Accuracy: 	 0.4750
Accuracy SD: 		 0.0247


In [24]:
print_score(clf, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.4867

Classification Report: 
                precision    recall  f1-score   support

      76TI#23       0.00      0.00      0.00        15
       Abshir       0.00      0.00      0.00        15
       Birhan       0.00      0.00      0.00        15
       Dekeba       0.71      1.00      0.83        15
Gambella_1107       0.44      1.00      0.61        15
       Gubiye       0.74      0.93      0.82        15
        Macia       0.52      0.93      0.67        15
       Meko-1       0.31      1.00      0.47        15
       Melkam       0.00      0.00      0.00        15
      Teshale       0.00      0.00      0.00        15

    micro avg       0.49      0.49      0.49       150
    macro avg       0.27      0.49      0.34       150
 weighted avg       0.27      0.49      0.34       150


Confusion Matrix: 
 [[ 0  0  0  1  9  1  4  0  0  0]
 [ 0  0  0  0  0  1  3 11  0  0]
 [ 0  0  0  0  0  0  0 15  0  0]
 [ 0  0  0 15  0  0  0  0  0  0]
 [ 0  0  0 

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [25]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier(random_state=101)
clf1.fit(X_train,y_train)

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=101, verbose=0, warm_start=False)

In [26]:
print_score(clf1, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.9971

Classification Report: 
                precision    recall  f1-score   support

      76TI#23       1.00      1.00      1.00        35
       Abshir       1.00      1.00      1.00        35
       Birhan       1.00      1.00      1.00        35
       Dekeba       0.97      1.00      0.99        35
Gambella_1107       1.00      1.00      1.00        35
       Gubiye       1.00      1.00      1.00        35
        Macia       1.00      1.00      1.00        35
       Meko-1       1.00      1.00      1.00        35
       Melkam       1.00      1.00      1.00        35
      Teshale       1.00      0.97      0.99        35

    micro avg       1.00      1.00      1.00       350
    macro avg       1.00      1.00      1.00       350
 weighted avg       1.00      1.00      1.00       350


Confusion Matrix: 
 [[35  0  0  0  0  0  0  0  0  0]
 [ 0 35  0  0  0  0  0  0  0  0]
 [ 0  0 35  0  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  0]
 [ 0  0  0

In [27]:
print_score(clf1, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.7400

Classification Report: 
                precision    recall  f1-score   support

      76TI#23       0.67      0.93      0.78        15
       Abshir       0.50      0.53      0.52        15
       Birhan       0.77      0.67      0.71        15
       Dekeba       0.81      0.87      0.84        15
Gambella_1107       0.94      1.00      0.97        15
       Gubiye       0.93      0.93      0.93        15
        Macia       0.63      0.80      0.71        15
       Meko-1       0.76      0.87      0.81        15
       Melkam       0.64      0.47      0.54        15
      Teshale       0.83      0.33      0.48        15

    micro avg       0.74      0.74      0.74       150
    macro avg       0.75      0.74      0.73       150
 weighted avg       0.75      0.74      0.73       150


Confusion Matrix: 
 [[14  1  0  0  0  0  0  0  0  0]
 [ 4  8  3  0  0  0  0  0  0  0]
 [ 0  5 10  0  0  0  0  0  0  0]
 [ 0  1  0 13  0  0  0  0  0  1]
 [ 0  0  0 

In [28]:
# Importing decision tree classifier from sklearn library
from sklearn.tree import DecisionTreeClassifier

# Fitting the decision tree with default hyperparameters, apart from
# max_depth which is 5 so that we can plot and read the tree.
dt_default = DecisionTreeClassifier()
dt_default.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [29]:
print_score(dt_default, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 1.0000

Classification Report: 
                precision    recall  f1-score   support

      76TI#23       1.00      1.00      1.00        35
       Abshir       1.00      1.00      1.00        35
       Birhan       1.00      1.00      1.00        35
       Dekeba       1.00      1.00      1.00        35
Gambella_1107       1.00      1.00      1.00        35
       Gubiye       1.00      1.00      1.00        35
        Macia       1.00      1.00      1.00        35
       Meko-1       1.00      1.00      1.00        35
       Melkam       1.00      1.00      1.00        35
      Teshale       1.00      1.00      1.00        35

    micro avg       1.00      1.00      1.00       350
    macro avg       1.00      1.00      1.00       350
 weighted avg       1.00      1.00      1.00       350


Confusion Matrix: 
 [[35  0  0  0  0  0  0  0  0  0]
 [ 0 35  0  0  0  0  0  0  0  0]
 [ 0  0 35  0  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  0]
 [ 0  0  0

In [30]:
print_score(dt_default, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.7400

Classification Report: 
                precision    recall  f1-score   support

      76TI#23       0.67      0.67      0.67        15
       Abshir       0.71      0.67      0.69        15
       Birhan       0.81      0.87      0.84        15
       Dekeba       0.77      0.67      0.71        15
Gambella_1107       1.00      1.00      1.00        15
       Gubiye       0.88      0.93      0.90        15
        Macia       0.67      0.67      0.67        15
       Meko-1       0.75      0.80      0.77        15
       Melkam       0.50      0.47      0.48        15
      Teshale       0.62      0.67      0.65        15

    micro avg       0.74      0.74      0.74       150
    macro avg       0.74      0.74      0.74       150
 weighted avg       0.74      0.74      0.74       150


Confusion Matrix: 
 [[10  2  0  0  0  0  0  0  1  2]
 [ 3 10  2  0  0  0  0  0  0  0]
 [ 0  2 13  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  1  0  0  0  4]
 [ 0  0  0 

In [32]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier(random_state=42)

# Importing decision tree classifier from sklearn library
from sklearn.tree import DecisionTreeClassifier

# Fitting the decision tree with default hyperparameters, apart from
# max_depth which is 5 so that we can plot and read the tree.
dt_default = DecisionTreeClassifier()

from sklearn import svm
clf = svm.SVC(kernel="linear")
clf.fit(X_train,y_train)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4,
                           p=2, metric='minkowski')

for i in range(1, 330, 1):
    from sklearn.decomposition import PCA as sklearnPCA
    sklearn_pca = sklearnPCA(n_components=i)
    X_sklearn = sklearn_pca.fit_transform(sg_x)
    df15 = pd.DataFrame(X_sklearn)
    X_train, X_test, y_train, y_test = train_test_split(X_sklearn, y,train_size=0.8,random_state=42,stratify = y)
    clf1 = clf1.fit(X_train,y_train)
    #print("i = {0}".format(i))
    #print("random forest")
    #print("accuracy score train: {0:.4f}\n".format(accuracy_score(y_train, clf1.predict(X_train))))
    if accuracy_score(y_test, clf1.predict(X_test)) >0.8:
        print("random_forest i = {0}".format(i))
        print("accuracy score test: {0:.4f}\n".format(accuracy_score(y_test, clf1.predict(X_test))))
    des = dt_default.fit(X_train, y_train)
    #print("decision tree")
    #print("accuracy score train: {0:.4f}\n".format(accuracy_score(y_train, des.predict(X_train))))
    if accuracy_score(y_test, des.predict(X_test)) >0.8:
        print("decision_tree i = {0}".format(i))
        print("accuracy score test: {0:.4f}\n".format(accuracy_score(y_test, des.predict(X_test))))
    clf=clf.fit(X_train,y_train)
    #print("svm")
    #print("accuracy score train: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
    if accuracy_score(y_test, clf.predict(X_test)) >0.8:
        print("svm i = {0}".format(i))
        print("accuracy score test: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
    knn =knn.fit(X_train, y_train)
    #print("knn")
    #print("accuracy score train: {0:.4f}\n".format(accuracy_score(y_train, knn.predict(X_train))))
    if accuracy_score(y_test, knn.predict(X_test)) >0.8:
        print("knn i = {0}".format(i))
        print("accuracy score test: {0:.4f}\n".format(accuracy_score(y_test, knn.predict(X_test))))
    

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement trai

random_forest i = 21
accuracy score test: 0.8100



C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are spe

random_forest i = 39
accuracy score test: 0.8100



C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are spe

random_forest i = 72
accuracy score test: 0.8200



C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are spe

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are spe

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are spe

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are spe

decision_tree i = 234
accuracy score test: 0.8100



C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are spe

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are spe

C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\akhil\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are spe